# Generated by Django 3.0.5 on 2020-04-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20200420_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.FileField(default='default.jpg', upload_to=''),
        ),
    ]
