# Generated by Django 3.0.5 on 2020-04-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20200420_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status_up',
            field=models.BooleanField(default=True),
        ),
    ]
